### ISSUE TITLE
Camera auto focus is not working

### ISSUE THREAD

**Issue by dyoxyne** [kefniark/UnityBarcodeScanner#20]
On the Unity example, the camera is not auto focusing. That can lead to blurry images and unrecognisable QR code.

I tried to do native Java plugin that sets the auto focus: http://stackoverflow.com/questions/19076316/how-to-ask-webcam-to-auto-focus-with-unity3d

The problem is I got an error when trying to access at the same time the camera: attempt to use a locked camera from a different process

Do you have any idea of how to fix this?

**Comment by kefniark** [comment]
As far as I know it is not possible in pure Unity. The auto focus is supposed to work by default.

You can try to add those kind of xcode, java plugins to add device specific operation, but it's up to your implementation and be careful about other device compatibility and later maintainability.

**Comment by dyoxyne** [comment]
I tested it and the auto focus was not working by default with a S7.
I also compared with the old qr code scanner plugin with the same phone, the auto focus was working.

I will do more research / test on it today.

**Comment by dyoxyne** [comment]
By the way, I found this: https://forum.unity3d.com/threads/webcamtexture-on-android-focus-mode-fix.327956/ and https://feedback.unity3d.com/suggestions/better-webcamtexture

It seems that it is IMPOSSIBLE without any hack to set some parameters for the camera only by using WebcamTexture / Unity C#.

**Comment by HertWili** [comment]
it is impossible to set autofocus by unity's webcamtexture component, especially on Samsung device and Nexus device.but maybe this plugin( [https://www.assetstore.unity3d.com/en/#!/content/56083](url) )on assetstore can help us ,it supports autofocus by publisher's native camera tool.
