### ISSUE TITLE
Camera not working when build from Unity to Xcode and run on iPhone

### ISSUE THREAD

**Issue by babman92** [kefniark/UnityBarcodeScanner#22]
Hi all, I build project unity to android and scanner woked. With iOS, have no effect.
i added NSCameraUsageDescription with value: $(PRODUCT_NAME) camera use.
In xcode general setting: Deployment target is 8.0
Please help me.

**Comment by luizzenha** [comment]
Hi,
I temporily fixed by adding the following lines in UnityAppController.mm
This will request the permission to access camera, but it is not reading any qrcode.
    
    if ([AVCaptureDevice respondsToSelector:@selector(requestAccessForMediaType: completionHandler:)]) {
        [AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL granted) {
            // Will get here on both iOS 7 & 8 even though camera permissions weren't required
            // until iOS 8. So for iOS 7 permission will always be granted.
            if (granted) {
                // Permission has been granted. Use dispatch_async for any UI updating
                // code because this block may be executed in a thread.
          
            } else {
                // Permission has been denied.
            }
        }];
    }

**Comment by luizzenha** [comment]
I Solved the problem, in the samples has a script called Boot.cs,  don't forget to add this script before init de qr code scene
