### ISSUE TITLE
ARCamera compatibility?

### ISSUE THREAD

**Issue by Pavel-Habzansky** [kefniark/UnityBarcodeScanner#28]
Question: Can your UnityBarcodeScanner work with ARCamera from Vuforia? It works wonders in normal mode, how can I use it for ARCamera?

**Comment by maximetinu** [comment]
Hi, I've create a class that works with Vuforia AR, check #30

**Comment by yosun** [comment]
Does not seem to work on iOS/Android device

ArgumentException: The Assembly zxing.unity is referenced by Assembly-CSharp-firstpass ('Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[

**Comment by yosun** [comment]
@Maximetinu  did you have to use a different zxing.a or .dll for iOS? 

@kefniark in your readme, you mention this works on iOS - however, though testing in editor, a code reads, i cannot get a code to read on actual iOS device. how did you set it up (different zxing libraries?) to run on iOS/Android devices?
