### ISSUE TITLE
Not working ons IOS

### ISSUE THREAD

**Issue by Mikedamen9** [kefniark/UnityBarcodeScanner#29]
I tried compiling the code on IOS and it does not seem to work for me.
All it does is shows a white raw image. 
It looks like it is not recognizing the camera. 
My unity version is: 2017.3.1f1
Xcode version: 9.2
IOS version: 9.x
I hope you can help me with this issue.
Note:
It works really good on android and windows good job :) 

EDIT: 
Xcode error: Exception: This Webcam Library can't work without the webcam authorization

**Comment by Mikedamen9** [comment]
#FIXED 
        Application.RequestUserAuthorization(UserAuthorization.WebCam);
Should fix the problem

**Comment by kefniark** [comment]
thanks for closing the issue

I will update the readme to make it more obvious

**Comment by johnymachine** [comment]
I had to comment out this section in Scanner class:

```csharp
if (!Application.HasUserAuthorization(UserAuthorization.WebCam))
{
    throw new Exception("This Webcam Library can't work without the webcam authorization");
}
```

It always fails on my IPad.

**Comment by kefniark** [comment]
Apparently you are not the only one having issues with this API on iOS
https://forum.unity.com/threads/checking-permissions-on-android-and-ios.479783/

worst case we can put this test inside a
```
#if UNITY_ANDROID
  ...
#endif
```

I like how some basic API can be so unreliable

**Comment by johnymachine** [comment]
Maybe more like:

```
#if !UNITY_IOS
  ...
#endif
```
