### ISSUE TITLE
Auto Focus on Android/iOS?

### ISSUE THREAD

**Issue by gclaret** [kefniark/UnityBarcodeScanner#33]
Hello, first of all, I wanted to thank you for this awesome repo. Had it up and running in minutes!

Is there any way to enable auto focus for mobile devices?

Thanks!

**Comment by kefniark** [comment]
So far I know, not directly through unity API, they dont expose auto focus features.
The only method I know require java code to interact directly with android API.

Related to this previous issue https://github.com/kefniark/UnityBarcodeScanner/issues/20
