### ISSUE TITLE
ARCore/ARKit Compatibility

### ISSUE THREAD

**Issue by yosun** [kefniark/UnityBarcodeScanner#34]
Having some issues trying to use the stream from ARCore with this.

**Comment by kefniark** [comment]
Can you provide more information please?
It's something I never tried and just the term "issues" is kinda fuzzy ^^
Cheers o/

**Comment by yosun** [comment]
How do you reference the stream for ARCore or ARkit?

**Comment by kefniark** [comment]
hum you are asking me question about another library I never used,
sorry but I don't think I can help you for this or anything related to **ARCore**.

This library is just a simple wrapper around unity API, so you can replace the part you dont want to use.
So for example, if you dont use the normal unity webcam, and want to use a 3rd party library, you have to write your own implementation of `IWebcam` or `IScanner`.
