### ISSUE TITLE
Activate camera light while scanning

### ISSUE THREAD

**Issue by Zorcher** [kefniark/UnityBarcodeScanner#35]
Hello,

I've been using this plugin and we've had no issues so far, however, having a way to turn the camera light on while camera is active will help with scanning codes in low light conditions.  Is there a way to incorporate this feature in a future release?

Zorcher

**Comment by MayckonJhonatas** [comment]
I have the same question

**Comment by kefniark** [comment]
Same than #47 
That's not related to this plugin or QR codes, that's an android question

the first answer in google: https://gist.github.com/GOROman/d403d39b34d7f99934fd

**Comment by MayckonJhonatas** [comment]
This isn't working
