### ISSUE TITLE
Open Front Camera for scanning

### ISSUE THREAD

**Issue by Arjunkakaiya** [kefniark/UnityBarcodeScanner#38]
Hey, You have done fantastic job..!!

Here is how I use it in my project. when you open the app QR Scanning is there for login purpose. Now I want the scanning camera to be front camera but not the back camera. I have searched the Plugin for front camera access but could not find one. 

I saw in project tab, There is card for multiple, I am not sure if that is the one which I am referring too.

**Comment by gabrieltva** [comment]
Hi,

you need to set the name of camera that you want to use. Like this:

```
ScannerSettings s = new ScannerSettings();
s.WebcamDefaultDeviceName = WebCamTexture.devices[1].name;
BarcodeScanner = new Scanner(s);
```

This code is to use the front camera of device (if exists).
So, to change the camera, you have to get the back camera name: `WebCamTexture.devices[0].name`.

I hope you understand. =)

**Comment by Arjunkakaiya** [comment]
Hey,

I figured it out just a few hours after, I posted. Just run a for loop to check which camera is front facing "WebCamTexture.devices[i].isFrontFacing" return that one if found else use first camera.

Thanks for the reply
