### ISSUE TITLE
Camera permissions on Android and IOS

### ISSUE THREAD

**Issue by ghost** [kefniark/UnityBarcodeScanner#41]
In the sample project above Samsung, the camera can be turned on normally, but the camera screen will be stuck at SONY before the screen appears, IOS will ask the camera permission

But when I packaged the package and imported it into my project, the IOS camera permissions were not accessed.
Where can I make changes?

**Comment by kefniark** [comment]
Project not supported anymore ([Here](https://github.com/kefniark/UnityBarcodeScanner/issues/48))
