### ISSUE TITLE
How to Run?

### ISSUE THREAD

**Issue by NightFury13** [kefniark/UnityBarcodeScanner#42]
Apologies if this comes off as too novice, but I can't seem to figure out how to work with this project? Can someone please help me with a few steps-to-follow? How do I run one of the samples (simple/continuous) or how do I use this inside a new Unity scene and scan codes?

The (little) documentation suggests copying `Assets/Scripts` into my project and using it. Can someone help me with more precise steps? Thanks!

**Comment by kefniark** [comment]
If you dont know how to use unity, I recommend watching youtube tutorials.
There are plenty of good resources for learning (people like brackeys)

For the precise steps:
* Copy the files in Assets/Scripts as you described
* Open this project in unity
* Open any sample scene you want to test
* Click run.

But this kind of plugin is really not plug and play, the scenes are just there as a sample ... at the end, it's an API you have to implement in your own project, which require some development and unity knowledge.
