### ISSUE TITLE
How can i keep the raw image size but not destort the view?

### ISSUE THREAD

**Issue by frederik0312** [kefniark/UnityBarcodeScanner#43]
Hello, i want to have my camera view to be a perfect square but if i keep the original raw image size the camera image is distorted. is there any way to just cut off some of the view, so the raw image box is my chossen size? 
Thanks

**Comment by kefniark** [comment]
Project not supported anymore ([Here](https://github.com/kefniark/UnityBarcodeScanner/issues/48))
