### ISSUE TITLE
How to switch camera

### ISSUE THREAD

**Issue by DKWIPL** [kefniark/UnityBarcodeScanner#49]
How to switch between front and back camera in android with this bar code reader?
Any help will be appreciated. 

Thank you,

**Comment by kefniark** [comment]
Project not supported anymore ([Here](https://github.com/kefniark/UnityBarcodeScanner/issues/48))

**Comment by DKWIPL** [comment]
-----------------------------------------------------------
Attention: Non-Delivery Report
-----------------------------------------------------------

This report is generated by the email server at:

       gophygital.io

The message with subject:

       "Re: [kefniark/UnityBarcodeScanner] How to switch camera (#49)"

and attached to this report was not delivered to 
the following recipients:

Address: ***@***.***
Reason:  User not found (550)
--------------
