### ISSUE TITLE
Crash with unity 5.5

### ISSUE THREAD

**Issue by kefniark** [kefniark/UnityBarcodeScanner#8]
# Description
Apparently, there are some crash with android since the update to unity 5.5

https://forum.unity3d.com/threads/camera-to-render-texture-crash.442663/

**Comment by dyoxyne** [comment]
It seems that
```
Webcam.Stop();
```
is the origin of the crash when the LoadScene is called.

**Comment by kefniark** [comment]
A proper issue was open by unity:
* https://issuetracker.unity3d.com/issues/android-crash-when-reloading-scene-which-uses-wecamtexture

**Reproducible:** 5.5.0b1, 5.5.0f3, 5.6.0a5 
**Not reproducible:** 5.4.3p2

**Comment by kefniark** [comment]
Got a notification from unity, they fixed the issue in the last patch version **5.5.0p4**

> ([855603](https://issuetracker.unity3d.com/product/unity/issues/guid/855603/?_ga=1.200687725.230263226.1477720546), [859268](https://issuetracker.unity3d.com/product/unity/issues/guid/859268/?_ga=1.193424878.230263226.1477720546)) - Android: Fixed a crash when reloading or resuming scene which uses WebCamTexture.

So this fix should arrive soon in the next **5.5.1** and be backported in **5.4.x** and **5.3.x** later
