### ISSUE TITLE
Wrong videoRotationAngle detected on unity 5.5

### ISSUE THREAD

**Issue by kefniark** [kefniark/UnityBarcodeScanner#9]
# Description
It seems on few devices with android 5.5, the videoRotationAngle is wrong.
Need to investigate to see if it's just updated few frames later or if it's a unity bug

**Comment by dyoxyne** [comment]
The videoRotationAngle is sometimes wrong when IScanner.OnReady is called.
By setting a small delay for OnReady, it seems to be a good hack for having a right videoRotationAngle ;p

**Comment by kefniark** [comment]
I added some debug log in the update loop and I get (only on android, works fine on unity editor) :
```csharp
Camera [Resolution:640x480, Orientation:-272, IsPlaying:True]
Camera [Resolution:640x480, Orientation:-90, IsPlaying:True]
Camera [Resolution:640x480, Orientation:-90, IsPlaying:True]
```
It seems that during one-two frame, the camera resolution is right but the orientation is not the final value yet ... this WebCam API really make no sense

**Comment by kefniark** [comment]
I have a solution to solve that which seems to work (need more testing).
I delay the OnReady function until the camera's informations are stable enough (at least N consecutive frames, for the moment set to 3 frames).
